name: Run Python Script and Commit SVG

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-and-commit:
    name: Update plot
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ github.event_name == 'push' && secrets.FG_ICECLASSIC || github.token }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python create_figure.py

    - name: Touch README
      run: touch README.md

    - name: Commit and push changes
      if: ${{ github.event_name == 'push' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add predictions.svg predictions_all.svg README.md
        git diff --staged --quiet || (git commit -m 'Update predictions*.svg' && git push)

    - name: Check for changes (PR validation only)
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git add predictions.svg predictions_all.svg README.md
        if ! git diff --staged --quiet; then
          echo "⚠️ The Python script generated changes to the SVG files."
          echo "A maintainer will need to run the script to update the files."
          git diff --staged --name-only
          exit 1
        else
          echo "✅ No changes needed to SVG files."
        fi
